version: "3.5"

services:
    # It sucks that the extend command has been removed in docker-compose 3.x
    unit-test-php-fpm:
        build:
            context: "./images/php-fpm"
            dockerfile: DockerfileXDebug
        container_name: "unit-test-php-fpm"
        environment:
            - "TEST_BASEURL"
            - "TEST_DB_HOST"
            - "TEST_DB_NAME"
            - "TEST_DB_USER"
            - "TEST_DB_PASSWORD"
        networks:
            - "vanilla_network"
        volumes:
            - "unit-test-shared:/shared" # expose php-fpm socket
            - "./logs/php-fpm:/var/log/php-fpm:delegated"
            - "./resources/certificates:/usr/local/share/ca-certificates:cached" # Mount extra certificates
            - "./resources/sphinx:/sphinx:cached" # expose sphinx API. We have to do this here because we need to be enable to update the plugin before we can start the container.
            - "../:/srv/vanilla-repositories:cached"


volumes:
    unit-test-shared:

networks:
    default:
        external:
            name: "vanilla_network"
